first_backend_website/config/routes.rb
Rails.application.routes.draw do
  get 'user_new', to: 'users_controller#new'
  get '/', to: 'static_pages#home'
  post 'user_new', to: 'users_controller#create', as: "user_create"
  get '/show/:id', to: 'users_controller#show', as: 'user'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

first_backend_website/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

first_backend_website/app/models/user.rb
class User < ApplicationRecord
end

first_backend_website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

first_backend_website/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def newUser
  end
end

first_backend_website/app/controllers/users_controller_controller.rb
class UsersControllerController < ApplicationController
  def new
    @copain = User.new
  end

  def create
    @copain = User.new
    @copain.name = params[:nom]
    @copain.mail = params[:mail]
    @copain.bio = params[:bio]
    @copain.pwd = params[:pwd]
    @copain.save
    redirect_to user_path(@copain)

    end


  def show
    @copain = User.find(params[:id])
  end
end

first_backend_website/app/helpers/application_helper.rb
module ApplicationHelper
end

first_backend_website/app/helpers/static_page_helper.rb
module StaticPageHelper
end

first_backend_website/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

first_backend_website/app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

first_backend_website/app/helpers/users_helper.rb
module UsersHelper
end

first_backend_website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstBackendWebsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

first_backend_website/app/views/static_page/user_controller.html.erb
<h1>StaticPage#user_controller</h1>
<p>Find me in app/views/static_page/user_controller.html.erb</p>

first_backend_website/app/views/static_pages/home.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Coucou le backend</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      <li><a href="user_new">Création d'utilisateur</a></li>
      <li><a href="#">Page 2</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="user_new"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
<div style="margin-left: 20%; margin-top:100px;">
<h1>Don't stop, never give up, lalala</h1>
  <p> Pour créer un utilisateur, clique sur la navbar, section "création d'utilisateur". Fait crtl+clic pour ouvrir dans un nouvel onglet et garder la musique</p>
  <br>
  <h2> Par Paul B., aka the minister of mixture </h2>
<iframe width="654" height="280" src="https://www.youtube.com/embed/GLQ0biK-ZgA?autoplay=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div>

first_backend_website/app/views/users_controller/new.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Coucou le backend</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      <li><a href="user_new">Création d'utilisateur</a></li>
      <li><a href="#">Page 2</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="user_new"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>

<h1>Coucou, créer ton identifiant et bienvenue dans la famille</h1>

<!-- ##############################################################
  Creation de mon form-->


<form class="form-horizontal" action="<%= user_create_path %>" method="POST" >
  <!-- L'action re-route vers mon fichier de création de user-->
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Name:</label>
    <div class="col-sm-5">
      <input type="name" class="form-control" id="name" placeholder="Enter name" name= "nom">
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Email:</label>
    <div class="col-sm-5">
      <input type="email" class="form-control" id="email" placeholder="Enter email" name= "mail">
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="bio">Quelques mots sur toi ?</label>
    <div class="col-sm-5">
      <input type="bio" class="form-control" id="bio" placeholder="Ta bio ?" name= "bio">
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="pwd">Mot de passe:</label>
    <div class="col-sm-5">
      <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pwd">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label><input type="checkbox"> Se souvenir de moi ?</label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default" method="GET">Submit</button>
    </div>
  </div>
</form>
-->

first_backend_website/app/views/users_controller/show.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Coucou le backend</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      <li><a href="user_new">Création d'utilisateur</a></li>
      <li><a href="#">Page 2</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="user_new"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
<div style="margin-left: 35%; margin-top:100px;">
<h1>Coucou </h1>
<p>Bienvenue sur ta page perso, <%= @copain.name %> <3 </p>
  <p> Voici ta bio, que tu as parfaitement remplie n'est ce pas ?</p>
  <p> <b><%=@copain.bio %></b>
    <p>
  <a  style="margin-top:30px;" class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Afficher ton mot de passe et ton mail ?
  </a>

</p>
<div class="collapse" id="collapseExample" >
  <div class="card card-body">
    <ul>
      <li><%= @copain.mail %></li>
      <li><%= @copain.pwd %></li>
  </div>
</div>
</div>